### PR TITLE
Removed memory management mechanics around retain(). Nothing is auto-…

### PR DESCRIPTION
**Pull request by wwwtyro**
…disposed any longer.

@flekschas @blubmin I've decided to remove the memory management mechanics around `retain()` and default everything to retained. My original purpose was to keep GPU memory management simple for one-off plots, but ultimately it feels awkward, confusing, and better-handled at a higher level of abstraction. I don't think this change requires code review (though certainly feel free to!), I mostly want to make sure I'm not forgetting something that would make this ex-feature a requirement or good idea. Thanks for any feedback!

### CODE REVIEW

**Comment by flekschas** [comment]
Thanks for the heads up! I am out on vacation but happy to take a look when I am back next week.

**Comment by wwwtyro** [comment]
I'm going to go ahead and merge this PR for now, but we can revisit the approach in the future if we discover issues. :slightly_smiling_face: :+1:

**Comment by flekschas** [comment]
Apologies, I totally forgot about the review. Thanks for simplifying the API! I like it and the code changes look good :)

**Comment by wwwtyro** [comment]
No worries at all, thanks for looking, glad it makes sense!

**Pull request merged**
