### PR TITLE
Enable tree shaking

### PR DESCRIPTION
**Pull request by flekschas**
I took a stab at #14 and **enabled tree shaking** by refactored the importing of scales, coordinates, primitives, and composites. This can bring down the final bundle size by **2-3x**.

### The Issue

Previously everything was imported to be able to references things via `cg.scale.linear` or `cg.rects`. While convenient, the problem with this approach was that the bundle size was quite large. I've setup a [very simple test](https://github.com/flekschas/candygraph-shake-test-old) where I am only using `Rects` and noticed that the bundle is **269.43kb** (brotli: 94.90kb).

Visualizing the bundle confirms that CandyGraph is currently not tree shakeable:

Screen Shot 2021-08-03 at 3 20 01 PM

### The Solution

To enable tree shaking, I've remove all scales, coordinates, primitives, and composites from the main CandyGraph class and instead exported them together with their factory functions. As a consequence, the convenient `cg.rects(...)` is replaced with `rects = createRects(cg, ...);`. The benefit is a much small bundle size. The [same app with this version of CandyGraph](https://github.com/flekschas/candygraph-shake-test-new) comes down to **114.22kb** (brotli: 32.60kb).

Here is a visualization showing that only the rects, linear, and cartesian components are included in the bundle and the dominating factor is really just regl.

Screen Shot 2021-08-03 at 3 07 28 PM

### API Changes

All convenience functions to scales, coordinates, primitives, and composites are replaced with simple factory functions.

For example:
- `cg.rects` is now `createRects(cg, ...)`
- `cg.reusableData` is now `createDataset(cg, data, auto = false)`

I've refactored the previous factory functions to not require currying.

For example:
```js
// Previously
import { factory as createRectFactory } from 'primitives/rects';
const createRects = createRectFactory(cg.regl);
const rects = createRects(...);

// Now
import { createRects } from 'primitives/rects';
const rects = createRects(cg, ...);
```

My rationale for this change is two-fold:
1. Simplicity: Currying is cool but it requires an extra line of code and adds complexity for newcomers
2. Consistency: Previously some functions were already factory functions like `createDataset` while others (like `createRectFactory`) were effectively functions that created factory functions. With the proposed change all facotry functions return instances.

Finally, I just want to say that I am happy to adjust things. To me this API change makes sense (while offering tree-shakability) and is still close to the original API, but there might be other things I didn't take into consideration.

### CODE REVIEW

**Review by wwwtyro — CHANGES_REQUESTED** [review]
This looks fantastic, thank you @flekschas! I agree with your design decisions here. I tried to push the paradigm I chose too far and ended up with something gross. This backs that out to something much nicer and gives us tree-shaking to boot. Awesome!

A couple requests: 

1. The tutorial broke a little bit. I have a fix PR [here](https://github.com/flekschas/candygraph/pull/1) if you want to use it, or you can just integrate the changes, whatever is easier for you.
2. Unless you don't want to, please add your info to authors in `package.json`.

**Comment by flekschas** [comment]
Thanks a lot for the review and fixing up the tutorial! I'll get it merged into this PR and update the `package.json` now.

**Comment by flekschas** [comment]
Alright, your PR is merged into this PR! Thanks a lot for fixing the issues I introduced.
And I added myself to the `contributors` in `package.json`. :)

**Comment by wwwtyro** [comment]
Looks great, thanks again! :tada:

**Pull request merged**
